openapi: 3.0.4
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /login:
    post:
      operationId: login
      summary: ログイン
      description: アカウント列挙攻撃対策として、認証NGは統一した応答を返す
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                username:
                  type: string
                  title: ユーザー名
                  maxLength: 16
                password:
                  type: string
                  title: パスワード
                  maxLength: 32
              required:
                - username
                - password
      responses:
        200:
          description: ログイン応答
          content:
            "application/json":
              schema:
                type: object
                properties:
                  name:
                    type: string
                    maxLength: 20
                  mailAddress:
                    type: string
                    maxLength: 256
                  role:
                    type: integer
                    enum:
                      - 0
                      - 1
                      - 2
                required:
                  - name
                  - role